
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('category_and_ingredient').del()
    .then(function () {
      // Inserts seed entries
      return knex('category_and_ingredient').insert([
        { id: 1, ingredient_category_id: 1, ingredient_id: 1 },
        { id: 2, ingredient_category_id: 1, ingredient_id: 2 },
        { id: 3, ingredient_category_id: 1, ingredient_id: 4 },
        { id: 4, ingredient_category_id: 1, ingredient_id: 5 },
        { id: 5, ingredient_category_id: 1, ingredient_id: 6 },
        { id: 6, ingredient_category_id: 1, ingredient_id: 7 },
        { id: 7, ingredient_category_id: 1, ingredient_id: 8 },
        { id: 8, ingredient_category_id: 1, ingredient_id: 9 },
        { id: 9, ingredient_category_id: 1, ingredient_id: 12 },
        { id: 10, ingredient_category_id: 1, ingredient_id: 13 },
        { id: 11, ingredient_category_id: 1, ingredient_id: 14 },
        { id: 12, ingredient_category_id: 1, ingredient_id: 15 },
        { id: 13, ingredient_category_id: 1, ingredient_id: 18 },
        { id: 14, ingredient_category_id: 2, ingredient_id: 1 },
        { id: 15, ingredient_category_id: 2, ingredient_id: 4 },
        { id: 16, ingredient_category_id: 2, ingredient_id: 6 },
        { id: 17, ingredient_category_id: 2, ingredient_id: 7 },
        { id: 18, ingredient_category_id: 2, ingredient_id: 8 },
        { id: 19, ingredient_category_id: 2, ingredient_id: 9 },
        { id: 20, ingredient_category_id: 2, ingredient_id: 12 },
        { id: 21, ingredient_category_id: 2, ingredient_id: 13 },
        { id: 22, ingredient_category_id: 2, ingredient_id: 14 },
        { id: 23, ingredient_category_id: 2, ingredient_id: 15 },
        { id: 24, ingredient_category_id: 2, ingredient_id: 18 },
        { id: 25, ingredient_category_id: 3, ingredient_id: 1 },
        { id: 26, ingredient_category_id: 3, ingredient_id: 2 },
        { id: 27, ingredient_category_id: 3, ingredient_id: 4 },
        { id: 28, ingredient_category_id: 3, ingredient_id: 5 },
        { id: 29, ingredient_category_id: 3, ingredient_id: 6 },
        { id: 30, ingredient_category_id: 3, ingredient_id: 7 },
        { id: 31, ingredient_category_id: 3, ingredient_id: 8 },
        { id: 32, ingredient_category_id: 3, ingredient_id: 9 },
        { id: 33, ingredient_category_id: 3, ingredient_id: 10 },
        { id: 34, ingredient_category_id: 3, ingredient_id: 11 },
        { id: 35, ingredient_category_id: 3, ingredient_id: 12 },
        { id: 36, ingredient_category_id: 3, ingredient_id: 13 },
        { id: 37, ingredient_category_id: 3, ingredient_id: 14 },
        { id: 38, ingredient_category_id: 3, ingredient_id: 15 },
        { id: 39, ingredient_category_id: 3, ingredient_id: 16 },
        { id: 40, ingredient_category_id: 3, ingredient_id: 17 },
        { id: 41, ingredient_category_id: 3, ingredient_id: 18 },
        { id: 42, ingredient_category_id: 3, ingredient_id: 19 },
        { id: 43, ingredient_category_id: 3, ingredient_id: 20 },
        { id: 44, ingredient_category_id: 3, ingredient_id: 21 },
        { id: 45, ingredient_category_id: 4, ingredient_id: 1 },
        { id: 46, ingredient_category_id: 4, ingredient_id: 2 },
        { id: 47, ingredient_category_id: 4, ingredient_id: 3 },
        { id: 48, ingredient_category_id: 4, ingredient_id: 5 },
        { id: 49, ingredient_category_id: 4, ingredient_id: 6 },
        { id: 50, ingredient_category_id: 4, ingredient_id: 8 },
        { id: 51, ingredient_category_id: 4, ingredient_id: 10 },
        { id: 52, ingredient_category_id: 4, ingredient_id: 11 },
        { id: 53, ingredient_category_id: 4, ingredient_id: 13 },
        { id: 54, ingredient_category_id: 4, ingredient_id: 14 },
        { id: 55, ingredient_category_id: 4, ingredient_id: 16 },
        { id: 56, ingredient_category_id: 4, ingredient_id: 17 },
        { id: 57, ingredient_category_id: 4, ingredient_id: 19 },
        { id: 58, ingredient_category_id: 4, ingredient_id: 20 },
        { id: 59, ingredient_category_id: 4, ingredient_id: 21 },
        { id: 60, ingredient_category_id: 5, ingredient_id: 1 },
        { id: 61, ingredient_category_id: 5, ingredient_id: 2 },
        { id: 62, ingredient_category_id: 5, ingredient_id: 3 },
        { id: 63, ingredient_category_id: 5, ingredient_id: 4 },
        { id: 64, ingredient_category_id: 5, ingredient_id: 5 },
        { id: 65, ingredient_category_id: 5, ingredient_id: 6 },
        { id: 66, ingredient_category_id: 5, ingredient_id: 8 },
        { id: 67, ingredient_category_id: 5, ingredient_id: 10 },
        { id: 68, ingredient_category_id: 5, ingredient_id: 11 },
        { id: 69, ingredient_category_id: 5, ingredient_id: 13 },
        { id: 70, ingredient_category_id: 5, ingredient_id: 14 },
        { id: 71, ingredient_category_id: 5, ingredient_id: 16 },
        { id: 72, ingredient_category_id: 5, ingredient_id: 17 },
        { id: 73, ingredient_category_id: 5, ingredient_id: 18 },
      ]);
    });
};
